BEGIN;

WITH seed_common_issues (item_name, issue_name, default_severity, default_urgency, is_other, is_active) AS (
    VALUES
        ('Bed Base', 'Broken frame', 'high', 'high', FALSE, TRUE),
        ('Bed Base', 'Loose legs', 'medium', 'medium', FALSE, TRUE),
        ('Bed Base', 'Noisy frame', 'low', 'low', FALSE, TRUE),
        ('Bed Base', 'Missing slats', 'high', 'high', FALSE, TRUE),
        ('Bed Base', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Mattress', 'Torn cover', 'medium', 'medium', FALSE, TRUE),
        ('Mattress', 'Dirty mattress', 'medium', 'medium', FALSE, TRUE),
        ('Mattress', 'Sagging mattress', 'medium', 'medium', FALSE, TRUE),
        ('Mattress', 'Infested mattress', 'critical', 'urgent', FALSE, TRUE),
        ('Mattress', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Chair', 'Broken chair', 'high', 'high', FALSE, TRUE),
        ('Chair', 'Loose backrest', 'medium', 'medium', FALSE, TRUE),
        ('Chair', 'Unstable chair', 'high', 'high', FALSE, TRUE),
        ('Chair', 'Missing chair', 'medium', 'medium', FALSE, TRUE),
        ('Chair', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Study Table', 'Broken table', 'high', 'high', FALSE, TRUE),
        ('Study Table', 'Loose legs', 'medium', 'medium', FALSE, TRUE),
        ('Study Table', 'Damaged surface', 'medium', 'medium', FALSE, TRUE),
        ('Study Table', 'Missing table', 'medium', 'medium', FALSE, TRUE),
        ('Study Table', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Wardrobe', 'Broken door', 'medium', 'medium', FALSE, TRUE),
        ('Wardrobe', 'Loose hinges', 'medium', 'medium', FALSE, TRUE),
        ('Wardrobe', 'Missing handle', 'low', 'low', FALSE, TRUE),
        ('Wardrobe', 'Cannot lock', 'medium', 'medium', FALSE, TRUE),
        ('Wardrobe', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('BookShelf', 'Broken shelf', 'medium', 'medium', FALSE, TRUE),
        ('BookShelf', 'Loose shelf', 'medium', 'medium', FALSE, TRUE),
        ('BookShelf', 'Unstable shelf', 'high', 'high', FALSE, TRUE),
        ('BookShelf', 'Missing shelf', 'medium', 'medium', FALSE, TRUE),
        ('BookShelf', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Food Rack', 'Broken rack', 'medium', 'medium', FALSE, TRUE),
        ('Food Rack', 'Rusty rack', 'medium', 'medium', FALSE, TRUE),
        ('Food Rack', 'Unstable rack', 'high', 'high', FALSE, TRUE),
        ('Food Rack', 'Missing rack', 'medium', 'medium', FALSE, TRUE),
        ('Food Rack', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Curtain', 'Torn curtain', 'low', 'low', FALSE, TRUE),
        ('Curtain', 'Dirty curtain', 'low', 'low', FALSE, TRUE),
        ('Curtain', 'Missing curtain', 'medium', 'medium', FALSE, TRUE),
        ('Curtain', 'Curtain too short', 'low', 'low', FALSE, TRUE),
        ('Curtain', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Fridge', 'Not cooling', 'high', 'high', FALSE, TRUE),
        ('Fridge', 'Leaking water', 'medium', 'medium', FALSE, TRUE),
        ('Fridge', 'Door not sealing', 'medium', 'medium', FALSE, TRUE),
        ('Fridge', 'Bad smell', 'medium', 'medium', FALSE, TRUE),
        ('Fridge', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Microwave', 'Not heating', 'medium', 'medium', FALSE, TRUE),
        ('Microwave', 'Sparking', 'critical', 'urgent', FALSE, TRUE),
        ('Microwave', 'Broken plate', 'low', 'low', FALSE, TRUE),
        ('Microwave', 'Door not closing', 'medium', 'medium', FALSE, TRUE),
        ('Microwave', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Kettle', 'Not boiling', 'medium', 'medium', FALSE, TRUE),
        ('Kettle', 'Leaking kettle', 'medium', 'medium', FALSE, TRUE),
        ('Kettle', 'Damaged cord', 'critical', 'urgent', FALSE, TRUE),
        ('Kettle', 'Missing kettle', 'medium', 'medium', FALSE, TRUE),
        ('Kettle', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Two-Plate Stove', 'Plate not heating', 'high', 'high', FALSE, TRUE),
        ('Two-Plate Stove', 'Faulty switch', 'high', 'high', FALSE, TRUE),
        ('Two-Plate Stove', 'Damaged cord', 'critical', 'urgent', FALSE, TRUE),
        ('Two-Plate Stove', 'Burnt plug', 'critical', 'urgent', FALSE, TRUE),
        ('Two-Plate Stove', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Iron', 'Not heating', 'medium', 'medium', FALSE, TRUE),
        ('Iron', 'Leaking water', 'low', 'low', FALSE, TRUE),
        ('Iron', 'Damaged cord', 'critical', 'urgent', FALSE, TRUE),
        ('Iron', 'Burnt soleplate', 'medium', 'medium', FALSE, TRUE),
        ('Iron', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Television', 'No picture', 'medium', 'medium', FALSE, TRUE),
        ('Television', 'No sound', 'medium', 'medium', FALSE, TRUE),
        ('Television', 'Remote missing', 'low', 'low', FALSE, TRUE),
        ('Television', 'Wall mount loose', 'high', 'high', FALSE, TRUE),
        ('Television', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Light Fitting', 'Light not working', 'medium', 'medium', FALSE, TRUE),
        ('Light Fitting', 'Flickering light', 'medium', 'medium', FALSE, TRUE),
        ('Light Fitting', 'Loose fitting', 'high', 'high', FALSE, TRUE),
        ('Light Fitting', 'Exposed wires', 'critical', 'urgent', FALSE, TRUE),
        ('Light Fitting', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Plug Point', 'Plug not working', 'high', 'high', FALSE, TRUE),
        ('Plug Point', 'Loose socket', 'high', 'high', FALSE, TRUE),
        ('Plug Point', 'Burn marks', 'critical', 'urgent', FALSE, TRUE),
        ('Plug Point', 'Exposed wires', 'critical', 'urgent', FALSE, TRUE),
        ('Plug Point', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Distribution Board', 'Tripping breaker', 'high', 'high', FALSE, TRUE),
        ('Distribution Board', 'No cover', 'critical', 'urgent', FALSE, TRUE),
        ('Distribution Board', 'Burning smell', 'critical', 'urgent', FALSE, TRUE),
        ('Distribution Board', 'Unlabelled switches', 'medium', 'medium', FALSE, TRUE),
        ('Distribution Board', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Extension Lead', 'Damaged cable', 'critical', 'urgent', FALSE, TRUE),
        ('Extension Lead', 'Overheating', 'critical', 'urgent', FALSE, TRUE),
        ('Extension Lead', 'Loose socket', 'high', 'high', FALSE, TRUE),
        ('Extension Lead', 'Missing extension', 'low', 'low', FALSE, TRUE),
        ('Extension Lead', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Toilet', 'Blocked toilet', 'high', 'urgent', FALSE, TRUE),
        ('Toilet', 'Leaking toilet', 'high', 'high', FALSE, TRUE),
        ('Toilet', 'Broken seat', 'medium', 'medium', FALSE, TRUE),
        ('Toilet', 'Not flushing', 'high', 'urgent', FALSE, TRUE),
        ('Toilet', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Shower', 'No hot water', 'high', 'high', FALSE, TRUE),
        ('Shower', 'Blocked drain', 'high', 'high', FALSE, TRUE),
        ('Shower', 'Leaking shower', 'medium', 'medium', FALSE, TRUE),
        ('Shower', 'Broken shower head', 'medium', 'medium', FALSE, TRUE),
        ('Shower', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Basin', 'Blocked basin', 'medium', 'medium', FALSE, TRUE),
        ('Basin', 'Leaking basin', 'medium', 'medium', FALSE, TRUE),
        ('Basin', 'Cracked basin', 'medium', 'medium', FALSE, TRUE),
        ('Basin', 'Loose basin', 'high', 'high', FALSE, TRUE),
        ('Basin', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Tap', 'Leaking tap', 'medium', 'medium', FALSE, TRUE),
        ('Tap', 'No water', 'high', 'urgent', FALSE, TRUE),
        ('Tap', 'Loose tap', 'medium', 'medium', FALSE, TRUE),
        ('Tap', 'Broken handle', 'medium', 'medium', FALSE, TRUE),
        ('Tap', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Geyser', 'No hot water', 'high', 'high', FALSE, TRUE),
        ('Geyser', 'Leaking geyser', 'critical', 'urgent', FALSE, TRUE),
        ('Geyser', 'Burst geyser', 'critical', 'urgent', FALSE, TRUE),
        ('Geyser', 'Tripping power', 'high', 'high', FALSE, TRUE),
        ('Geyser', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Door Lock', 'Lock not working', 'high', 'urgent', FALSE, TRUE),
        ('Door Lock', 'Key stuck', 'medium', 'high', FALSE, TRUE),
        ('Door Lock', 'Key missing', 'medium', 'medium', FALSE, TRUE),
        ('Door Lock', 'Loose lock', 'high', 'high', FALSE, TRUE),
        ('Door Lock', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Burglar Bars', 'Loose burglar bars', 'high', 'high', FALSE, TRUE),
        ('Burglar Bars', 'Broken burglar bars', 'high', 'high', FALSE, TRUE),
        ('Burglar Bars', 'Rusty burglar bars', 'medium', 'medium', FALSE, TRUE),
        ('Burglar Bars', 'Missing burglar bars', 'high', 'urgent', FALSE, TRUE),
        ('Burglar Bars', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Security Gate', 'Gate not closing', 'high', 'high', FALSE, TRUE),
        ('Security Gate', 'Gate lock faulty', 'high', 'urgent', FALSE, TRUE),
        ('Security Gate', 'Gate off track', 'high', 'high', FALSE, TRUE),
        ('Security Gate', 'Remote not working', 'medium', 'medium', FALSE, TRUE),
        ('Security Gate', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('CCTV Camera', 'Camera offline', 'high', 'high', FALSE, TRUE),
        ('CCTV Camera', 'Blurry footage', 'medium', 'medium', FALSE, TRUE),
        ('CCTV Camera', 'Camera damaged', 'high', 'high', FALSE, TRUE),
        ('CCTV Camera', 'No recording', 'high', 'high', FALSE, TRUE),
        ('CCTV Camera', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Fire Extinguisher', 'Missing extinguisher', 'critical', 'urgent', FALSE, TRUE),
        ('Fire Extinguisher', 'Expired extinguisher', 'critical', 'urgent', FALSE, TRUE),
        ('Fire Extinguisher', 'Pressure low', 'high', 'urgent', FALSE, TRUE),
        ('Fire Extinguisher', 'Damaged seal', 'high', 'high', FALSE, TRUE),
        ('Fire Extinguisher', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Waste Bin', 'Missing bin', 'low', 'low', FALSE, TRUE),
        ('Waste Bin', 'Broken bin', 'low', 'low', FALSE, TRUE),
        ('Waste Bin', 'Overflowing bin', 'medium', 'medium', FALSE, TRUE),
        ('Waste Bin', 'Dirty bin', 'medium', 'medium', FALSE, TRUE),
        ('Waste Bin', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Mop Bucket', 'Broken bucket', 'low', 'low', FALSE, TRUE),
        ('Mop Bucket', 'Missing bucket', 'low', 'low', FALSE, TRUE),
        ('Mop Bucket', 'Dirty bucket', 'low', 'low', FALSE, TRUE),
        ('Mop Bucket', 'Wheels broken', 'low', 'low', FALSE, TRUE),
        ('Mop Bucket', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Soap Dispenser', 'Empty dispenser', 'low', 'low', FALSE, TRUE),
        ('Soap Dispenser', 'Broken dispenser', 'low', 'low', FALSE, TRUE),
        ('Soap Dispenser', 'Leaking dispenser', 'low', 'low', FALSE, TRUE),
        ('Soap Dispenser', 'Missing dispenser', 'low', 'low', FALSE, TRUE),
        ('Soap Dispenser', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Toilet Brush', 'Missing brush', 'low', 'low', FALSE, TRUE),
        ('Toilet Brush', 'Dirty brush', 'low', 'low', FALSE, TRUE),
        ('Toilet Brush', 'Broken holder', 'low', 'low', FALSE, TRUE),
        ('Toilet Brush', 'Needs replacement', 'low', 'low', FALSE, TRUE),
        ('Toilet Brush', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Door', 'Door not closing', 'high', 'high', FALSE, TRUE),
        ('Door', 'Door damaged', 'high', 'high', FALSE, TRUE),
        ('Door', 'Loose hinges', 'medium', 'medium', FALSE, TRUE),
        ('Door', 'Hole in door', 'medium', 'medium', FALSE, TRUE),
        ('Door', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Ceiling', 'Ceiling leak', 'high', 'urgent', FALSE, TRUE),
        ('Ceiling', 'Ceiling crack', 'medium', 'medium', FALSE, TRUE),
        ('Ceiling', 'Ceiling sagging', 'critical', 'urgent', FALSE, TRUE),
        ('Ceiling', 'Mould on ceiling', 'high', 'high', FALSE, TRUE),
        ('Ceiling', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Curtain Rail', 'Loose rail', 'medium', 'medium', FALSE, TRUE),
        ('Curtain Rail', 'Broken rail', 'medium', 'medium', FALSE, TRUE),
        ('Curtain Rail', 'Missing rail', 'medium', 'medium', FALSE, TRUE),
        ('Curtain Rail', 'Hooks missing', 'low', 'low', FALSE, TRUE),
        ('Curtain Rail', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Floor', 'Cracked floor', 'medium', 'medium', FALSE, TRUE),
        ('Floor', 'Loose tiles', 'high', 'high', FALSE, TRUE),
        ('Floor', 'Wet floor', 'high', 'urgent', FALSE, TRUE),
        ('Floor', 'Uneven floor', 'high', 'high', FALSE, TRUE),
        ('Floor', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Window', 'Broken window', 'high', 'urgent', FALSE, TRUE),
        ('Window', 'Window not closing', 'high', 'high', FALSE, TRUE),
        ('Window', 'Cracked glass', 'high', 'high', FALSE, TRUE),
        ('Window', 'Loose frame', 'medium', 'medium', FALSE, TRUE),
        ('Window', 'Other issue', 'medium', 'medium', TRUE, TRUE),
        ('Notice Board', 'Board damaged', 'low', 'low', FALSE, TRUE),
        ('Notice Board', 'Board missing', 'low', 'low', FALSE, TRUE),
        ('Notice Board', 'Loose board', 'medium', 'medium', FALSE, TRUE),
        ('Notice Board', 'Cannot pin notices', 'low', 'low', FALSE, TRUE),
        ('Notice Board', 'Other issue', 'medium', 'medium', TRUE, TRUE)
),
resolved_common_issues AS (
    SELECT
        (
            substr(md5(items.id::text || ':' || seed_common_issues.issue_name), 1, 8) || '-' ||
            substr(md5(items.id::text || ':' || seed_common_issues.issue_name), 9, 4) || '-' ||
            substr(md5(items.id::text || ':' || seed_common_issues.issue_name), 13, 4) || '-' ||
            substr(md5(items.id::text || ':' || seed_common_issues.issue_name), 17, 4) || '-' ||
            substr(md5(items.id::text || ':' || seed_common_issues.issue_name), 21, 12)
        )::uuid AS id,
        items.id AS item_id,
        seed_common_issues.issue_name,
        seed_common_issues.default_severity,
        seed_common_issues.default_urgency,
        seed_common_issues.is_other,
        seed_common_issues.is_active
    FROM seed_common_issues
    JOIN items
        ON items.name = seed_common_issues.item_name
)
INSERT INTO common_issues (
    id,
    item_id,
    issue_name,
    default_severity,
    default_urgency,
    is_other,
    is_active
)
SELECT
    id,
    item_id,
    issue_name,
    default_severity,
    default_urgency,
    is_other,
    is_active
FROM resolved_common_issues
ON CONFLICT (item_id, issue_name) DO UPDATE
SET
    default_severity = EXCLUDED.default_severity,
    default_urgency = EXCLUDED.default_urgency,
    is_other = EXCLUDED.is_other,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

COMMIT;
